#'Plot out all the percentage of Latin honors based on one origin for the past 16 years
#' @param option latin Honor: Summa, Magna, or Cum
#' @param verifier chinese,cantonese, or japanese origin
#' @return the percentage of certain latin honor during the past 16 years
#' @examples
#' read ("Summa", chineseLastNames)
#'
read <- function(option,verifier){
  y <- vector()
  #list out all the years
  year <-c ("2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016")
  print(option)
  if(option == "Summa"){
    x<-readHonor(Data2002, verifier)
    # read the percentage column from different years...
    y<-c(y,with(x,SummaPer)[1])
    x<-readHonor(Data2003, verifier)
    y<-c(y,with(x,SummaPer)[1])
    x<-readHonor(Data2004, verifier)
    y<-c(y,with(x,SummaPer)[1])
   x<-readHonor(Data2005, verifier)
   y<-c(y,with(x,SummaPer)[1])
   x<-readHonor(Data2006, verifier)
   y<-c(y,with(x,SummaPer)[1])
   x<-readHonor(Data2007, verifier)
  y<-c(y,with(x,SummaPer)[1])
   x<-readHonor(Data2008, verifier)
   y<-c(y,with(x,SummaPer)[1])
  x<-readHonor(Data2009, verifier)
    y<-c(y,with(x,SummaPer)[1])
  x<-readHonor(Data2010, verifier)
  y<-c(y,with(x,SummaPer)[1])
  x<-readHonor(Data2011, verifier)
  y<-c(y,with(x,SummaPer)[1])
  x<-readHonor(Data2012, verifier)
  y<-c(y,with(x,SummaPer)[1])
  x<-readHonor(Data2013, verifier)
  y<-c(y,with(x,SummaPer)[1])
  x<-readHonor(Data2014, verifier)
  y<-c(y,with(x,SummaPer)[1])
  x<-readHonor(Data2015, verifier)
  y<-c(y,with(x,SummaPer)[1])
  x<-readHonor(Data2016, verifier)
  y<-c(y,with(x,SummaPer)[1])
  }
  if(option == "Magna"){
    x<-readHonor(Data2002, verifier)
    #read the magna percentage from each year
    y<-c(y,with(x,MagnaAbovePer)[1])
    x<-readHonor(Data2003, verifier)
    y<-c(y,with(x,MagnaAbovePer)[1])
    x<-readHonor(Data2004, verifier)
    y<-c(y,with(x,MagnaAbovePer)[1])
    x<-readHonor(Data2005, verifier)
    y<-c(y,with(x,MagnaAbovePer)[1])
    x<-readHonor(Data2006, verifier)
    y<-c(y,with(x,MagnaAbovePer)[1])
    x<-readHonor(Data2007, verifier)
    y<-c(y,with(x,MagnaAbovePer)[1])
    x<-readHonor(Data2008, verifier)
    y<-c(y,with(x,MagnaAbovePer)[1])
    x<-readHonor(Data2009, verifier)
    y<-c(y,with(x,MagnaAbovePer)[1])
    x<-readHonor(Data2010, verifier)
    y<-c(y,with(x,MagnaAbovePer)[1])
    x<-readHonor(Data2011, verifier)
    y<-c(y,with(x,MagnaAbovePer)[1])
    x<-readHonor(Data2012, verifier)
    y<-c(y,with(x,MagnaAbovePer)[1])
    x<-readHonor(Data2013, verifier)
    y<-c(y,with(x,MagnaAbovePer)[1])
    x<-readHonor(Data2014, verifier)
    y<-c(y,with(x,MagnaAbovePer)[1])
    x<-readHonor(Data2015, verifier)
    y<-c(y,with(x,MagnaAbovePer)[1])
    x<-readHonor(Data2016, verifier)
    y<-c(y,with(x,MagnaAbovePer)[1])
  }
  if(option == "Cum"){
    x<-readHonor(Data2002, verifier)
    y<-c(y,with(x,CumAbovePer)[1])
    x<-readHonor(Data2003, verifier)
    y<-c(y,with(x,CumAbovePer)[1])
    x<-readHonor(Data2004, verifier)
    y<-c(y,with(x,CumAbovePer)[1])
    x<-readHonor(Data2005, verifier)
    y<-c(y,with(x,CumAbovePer)[1])
    x<-readHonor(Data2006, verifier)
    y<-c(y,with(x,CumAbovePer)[1])
    x<-readHonor(Data2007, verifier)
    y<-c(y,with(x,CumAbovePer)[1])
    x<-readHonor(Data2008, verifier)
    y<-c(y,with(x,CumAbovePer)[1])
    x<-readHonor(Data2009, verifier)
    y<-c(y,with(x,CumAbovePer)[1])
    x<-readHonor(Data2010, verifier)
    y<-c(y,with(x,CumAbovePer)[1])
    x<-readHonor(Data2011, verifier)
    y<-c(y,with(x,CumAbovePer)[1])
    x<-readHonor(Data2012, verifier)
    y<-c(y,with(x,CumAbovePer)[1])
    x<-readHonor(Data2013, verifier)
    y<-c(y,with(x,CumAbovePer)[1])
    x<-readHonor(Data2014, verifier)
    y<-c(y,with(x,CumAbovePer)[1])
    x<-readHonor(Data2015, verifier)
    y<-c(y,with(x,CumAbovePer)[1])
    x<-readHonor(Data2016, verifier)
    y<-c(y,with(x,CumAbovePer)[1])
  }
  #return percentage over year"=
  output<- data.frame(year = year,percent=y)
  output
}
